[project]
name = "aes-scrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "google>=3.0.0",
    "gspread>=6.1.4",
    "oauth2client>=4.1.3",
    "requests>=2.32.3",
]
